### ISSUE TITLE
Weakly typed view models

### ISSUE THREAD

**Issue by PetrSvirak** [MacakM/PV247-Expense-Manager#44]
Do not use _ViewData_ or _TempData_ within controllers. I went through the usage and all is either a property missing in a view model or resource string.

**Comment by mayoturis** [comment]
I tried to replace all ViewData and TempData, but in two situations I didn't know how to proceed:
- Sending "flash" message after redirect ... When some action happened and I want to redirect user and then show him message about that action there. I don't how to do this without TempData (or other usage of Session). For example this method: https://github.com/MacakM/PV247-Expense-Manager/blob/master/PV247/ExpenseManager.Presentation/Controllers/ExpenseController.cs#L174 It could be probably done by parameter in action methods which can display that message, but it will require a lot of otherwise unnecessary and duplicated code.
- Sending some variable to _layout (or all views). E.g. email of currently authenticated user which will be visible on every page.  It could be done using ViewModel but then it would have to be in every single action method. If I want to do it in one place (currently it is done in BaseController but probably will be changed in future) I don't have access to ViewModel since I don't know which one I will use.

**Comment by PetrSvirak** [comment]
The answer to both is, quite frankly, partial actions. There could be a "shared" controller (containing simple actions used across other actions) or helper methods used both used in partial views that would be part of either _layout or given views.

In the first case, it should be OK to pass resource string or another identifier as URL parameter of the redirect. Common actions would, of course, ignore it; however, a partial action or a helper method would read it and render a message. A sample can be found in the sign-in action of scaffolded solution (redirectUrl parameter). Rendering could even be done on _layout, only render nothing if there is no message.

In the second case, this is a pretty same problem. On _layout, there could be a partial action that is call every time it is rendered. The action would read email based on information stored in session or cookie or where ever you store authentication information. 

When the code is simple enough, you can use just a partial view (without partial action), yet it is usually considered to be a good practice to create a controller and action for each partial view. In MVC6, view components were introduced as a replacement for (action-less) partial views: http://stackoverflow.com/a/29823923/1138663. I would recommend you to go this way.

**Comment by PetrSvirak** [comment]
First of all, the _~Views\Partial_ folder should not exist. The default path for components' views is _``~\View\[\<ControllerName>|Shared]\Components\<ComponentName>\Default.cshtml``_ - I see no reason not to stick with it - no view name would have to be specified in components this way.

Second, there is absolutely no need for _SuccessMessageViewModel_ to exists; simply use _string_ as the model. The only thing that needs to be done in ViewComponent is to explicitly use generic type for the type of model when using _View_ method.

Third, does UserEmail component really have to exists? There is ``User.Identity.Name`` that seems to possess same value - this way you can omit extra database access.

Fourth, following lines of code repeat for several times: 
````
@if (Model.ErrorMessage != null)
{
	<div class="alert alert-danger">
		<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		@Model.ErrorMessage
	</div>
}
````
 What you need to do here is:
* either introduce an interface that will ensure the ErrorMessage property is implemented (mind you, only getter is part of the contract here) and let all necessary models implement that interface; then create a partial view that will accept the interface as the model and that will produce the message (replacing repetitive code with simple single line partial view call).
* or take the very same approach as the one for successful messages. In fact, that is where multiple views could be part of one component that would care about showing state messages to the user (even in this case, default folder structure should still be used for placing razor templates).
