### ISSUE TITLE
TestSeedingInitializer is part of production code

### ISSUE THREAD

**Issue by PetrSvirak** [MacakM/PV247-Expense-Manager#60]
If the name is correct, then the ExpenseManager.Database project is not a place for the class. Move this class to the test project where it belongs. Since the database should have been well tested in ExpenseManager.Database.Tests, there should be no need for this initializer in ExpenseManager.Business.Tests; however, as you decided to omit these layer of testing, you make things pretty nasty here. Anyway. ExpenseManager.Presentation.Tests definitely do not need the initializer as it does not production. Also, seeding should be part of DbMigrationsConfiguration. If you really wanted use pre-seeded migrations, use the standalone application to provide migrations and custom configuration to seed the database.

**Comment by mayoturis** [comment]
This class was just for me to see that when I run the application, everything looks like it should without the need to create new entities manually. Originally I didn't want to push it to repository but since I thought somebody else might want to use it I did. It was planned to remove it before the production, no code currently uses this class (except the one I have locally of course).

**Comment by PetrSvirak** [comment]
Fair enough. Why is this not stated in the class API doc?
Fix the API doc for this class and close the issue. 
You might have established (at least) a development branch if you wanted to share some not-production code. Production code is supposed to be ready to deploy all the time...
